In [2]:
import numpy as np
import importlib as imp
import decentralized_monitoring as dm
import pickle
imp.reload(dm)

<module 'decentralized_monitoring' from 'C:\\Document_Z\\Code\\iot-monitoring\\decentralized_monitoring.py'>

In [3]:
with open('data/data_correlated_stream.pkl', 'rb') as f:
    data_dict = pickle.load(f)
data_ic = data_dict['data_ic']
data_ol = [data_dict['data1'], data_dict['data2'], data_dict['data3']]

### Quants
#### Identical edge devices
##### m=2

In [18]:
%%time
#90.75: 364.06, 90.80: 366.96, 90.85: 371.68
distribution_type = [1, 2, 3, 4, 5] * 10
n_ic = 500
r, k, d = 3, 1, 10
n_observe = 2
h = 90.85
dm.arl_quants(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, r=r, h=h, k=k, d=d,
              n_thread=15, N=10000, verbose=1)

90.85	371.68	3.94
CPU times: total: 15.6 ms
Wall time: 4min 59s


(371.6792, 3.9363406418571043)

In [19]:
%%time
size_list = [1, 2, 3]
for size_shift in size_list:
    dm.arl_quants(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, r=r, h=h, k=k, d=d,
                  n_shift=2, size_shift=size_shift, t_shift=30, n_thread=15, N=10000, verbose=1)

90.85	106.47	1.00
90.85	67.65	0.61
90.85	62.49	0.56
CPU times: total: 31.2 ms
Wall time: 4min 25s


##### $m=4$

In [24]:
%%time
# 90.85: 365.32, 90.90: 365.57, 90.95: 364.87, 91: 372.15
distribution_type = [1, 2, 3, 4, 5] * 10
n_ic = 500
r, k, d = 3, 1, 10
n_observe = 4
h = 91.00
dm.arl_quants(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, r=r, h=h, k=k, d=d,
              n_thread=15, N=10000, verbose=1)

91.00	372.15	3.75
CPU times: total: 0 ns
Wall time: 5min 15s


(372.1517, 3.7466526592027445)

In [25]:
%%time
size_list = [1, 2, 3]
for size_shift in size_list:
    dm.arl_quants(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, r=r, h=h, k=k, d=d,
                  n_shift=2, size_shift=size_shift, t_shift=30, n_thread=15, N=10000, verbose=1)

91.00	70.04	0.59
91.00	39.42	0.31
91.00	34.36	0.27
CPU times: total: 0 ns
Wall time: 3min 21s


##### $m=6$

In [27]:
%%time
# 91: 357.62, 91.1: 368.72
distribution_type = [1, 2, 3, 4, 5] * 10
n_ic = 500
r, k, d = 3, 1, 10
n_observe = 6
h = 91.10
dm.arl_quants(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, r=r, h=h, k=k, d=d,
              n_thread=15, N=10000, verbose=1)

91.10	368.72	3.67
CPU times: total: 0 ns
Wall time: 5min 5s


(368.7193, 3.674835483494602)

In [28]:
%%time
size_list = [1, 2, 3]
for size_shift in size_list:
    dm.arl_quants(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, r=r, h=h, k=k, d=d,
                  n_shift=2, size_shift=size_shift, t_shift=30, n_thread=15, N=10000, verbose=1)

91.10	54.48	0.44
91.10	28.67	0.22
91.10	25.10	0.19
CPU times: total: 62.5 ms
Wall time: 2min 52s


##### $m=50$

In [32]:
%%time
# 91.1: 303.32, 91.5: 313.00, 93:
distribution_type = [1, 2, 3, 4, 5] * 10
n_ic = 500
r, k, d = 3, 1, 10
n_observe = 50
h = 93.00
dm.arl_quants(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, r=r, h=h, k=k, d=d,
              n_thread=15, N=10000, verbose=1)

93.00	369.97	3.72
CPU times: total: 15.6 ms
Wall time: 5min 49s


(369.9655, 3.7154755080574815)

In [33]:
%%time
size_list = [1, 2, 3]
for size_shift in size_list:
    dm.arl_quants(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, r=r, h=h, k=k, d=d,
                  n_shift=2, size_shift=size_shift, t_shift=30, n_thread=15, N=10000, verbose=1)

93.00	21.18	0.15
93.00	8.78	0.06
93.00	7.11	0.05
CPU times: total: 31.2 ms
Wall time: 2min 19s


### QH01
#### Identical edge devices

In [74]:
imp.reload(dm)

<module 'decentralized_monitoring' from 'C:\\Document_Z\\Code\\iot-monitoring\\decentralized_monitoring.py'>

In [94]:
%%time
distribution_type = [1, 2, 3, 4, 5] * 10
n_ic = 500
k = 0.05
h = 2000
dm.rl_qh(distribution_type=distribution_type, n_ic=n_ic, h=h, k=1, n_shift=None, size_shift=1, t_shift=30)

1259428.8112548385 302.3279142596813
CPU times: total: 0 ns
Wall time: 5 ms


4

In [73]:
dm.rl_qh(distribution_type=distribution_type, n_ic=n_ic, h=h, k=1, n_shift=2, size_shift=1, t_shift=30)

1526.563198835592 13450.01998128221


628

### SRAS full
#### Identical edge devices

In [15]:
%%time
# 4.412: 364.01, 4.414:
distribution_type = [1, 2, 3, 4, 5] * 10
n_ic = 500
lambda_ = 0.1
h = 4.414
dm.arl_SRAS_full(distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, n_thread=15, N=10000, verbose=1)

4.41	369.42	3.69
CPU times: total: 0 ns
Wall time: 2min 45s


(369.4224, 3.686852955818011)

In [16]:
%%time
size_list = [1, 2, 3]
for size_shift in size_list:
    dm.arl_SRAS_full(distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, n_shift=2, size_shift=size_shift, t_shift=30,
                     n_thread=15, N=10000, verbose=1)

4.41	15.88	0.08
4.41	6.04	0.02
4.41	4.11	0.01
CPU times: total: 93.8 ms
Wall time: 1min 27s


### SRAS
#### Identical edge devices
##### $m=2$

In [61]:
imp.reload(dm)

<module 'decentralized_monitoring' from 'C:\\Document_Z\\Code\\iot-monitoring\\decentralized_monitoring.py'>

In [69]:
%%time
distribution_type = [1, 2, 3, 4, 5] * 10
n_ic = 500
lambda_ = 0.1
bandwidth = 1.5
delta = 0.08
n_observe = 2
h = 1.963
dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
            delta=delta, n_thread=15, N=10000, verbose=1)

1.96	372.36	3.83
CPU times: total: 0 ns
Wall time: 1min 56s


(372.3552, 3.826820184343132)

In [70]:
%%time
size_list = [1, 2, 3]
for size_shift in size_list:
    dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
                delta=delta, n_shift=2, size_shift=size_shift, t_shift=30, n_thread=15, N=10000, verbose=1)

1.96	265.19	3.40
1.96	262.57	3.43
1.96	260.28	3.33
CPU times: total: 31.2 ms
Wall time: 4min 37s


##### $m=4$

In [79]:
%%time
distribution_type = [1, 2, 3, 4, 5] * 10
n_ic = 500
lambda_ = 0.1
bandwidth = 1.5
delta = 0.08
n_observe = 4
h = 2.53
dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
            delta=delta, n_thread=15, N=10000, verbose=1)

2.53	369.66	3.72
CPU times: total: 0 ns
Wall time: 1min 52s


(369.6601, 3.716194324412947)

In [80]:
%%time
size_list = [1, 2, 3]
for size_shift in size_list:
    dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
                delta=delta, n_shift=2, size_shift=size_shift, t_shift=30, n_thread=15, N=10000, verbose=1)

2.53	229.41	3.34
2.53	220.05	3.19
2.53	217.22	3.22
CPU times: total: 0 ns
Wall time: 3min 51s


##### $m=6$

In [88]:
%%time
distribution_type = [1, 2, 3, 4, 5] * 10
n_ic = 500
lambda_ = 0.1
bandwidth = 1.5
delta = 0.08
n_observe = 6
h = 2.934
dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
            delta=delta, n_thread=15, N=10000, verbose=1)

2.93	370.33	3.69
CPU times: total: 15.6 ms
Wall time: 2min 16s


(370.3266, 3.685375127886441)

In [89]:
%%time
size_list = [1, 2, 3]
for size_shift in size_list:
    dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
                delta=delta, n_shift=2, size_shift=size_shift, t_shift=30, n_thread=15, N=10000, verbose=1)

2.93	205.40	3.20
2.93	200.79	3.19
2.93	197.47	3.16
CPU times: total: 0 ns
Wall time: 4min 45s


#### Distinct edge devices
##### $m=2$

In [100]:
%%time
distribution_type = [1, 2, 3, 4, 5] * 5 + [1, 2, 3, 4, 5, 1, 2, 3, 4, 5] * 5
n_ic = 500
lambda_ = 0.1
bandwidth = 1.5
delta = 0.08
n_observe = 2
h = 0.91
dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
            delta=delta, n_thread=15, N=10000, verbose=1)

0.91	372.43	3.84
CPU times: total: 93.8 ms
Wall time: 3min 37s


(372.4344, 3.8385804367844116)

In [104]:
%%time
size_list = [1, 2, 3]
for size_shift in size_list:
    dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
                delta=delta, n_shift=2, size_shift=size_shift, t_shift=30, n_thread=15, N=10000, verbose=1)

0.91	287.71	3.53
0.91	292.92	3.59
0.91	283.02	3.45
CPU times: total: 0 ns
Wall time: 8min 5s


##### $m=4$

In [115]:
%%time
distribution_type = [1, 2, 3, 4, 5] * 5 + [1, 2, 3, 4, 5, 1, 2, 3, 4, 5] * 5
n_ic = 500
lambda_ = 0.1
bandwidth = 1.5
delta = 0.08
n_observe = 4
h = 1.208
dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
            delta=delta, n_thread=15, N=10000, verbose=1)

1.21	370.69	3.70
CPU times: total: 0 ns
Wall time: 4min 8s


(370.6866, 3.7017809738076077)

In [116]:
%%time
size_list = [1, 2, 3]
for size_shift in size_list:
    dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
                delta=delta, n_shift=2, size_shift=size_shift, t_shift=30, n_thread=15, N=10000, verbose=1)

1.21	250.01	3.41
1.21	237.55	3.23
1.21	234.24	3.14
CPU times: total: 0 ns
Wall time: 10min 29s


##### $m=6$

In [122]:
%%time
distribution_type = [1, 2, 3, 4, 5] * 5 + [1, 2, 3, 4, 5, 1, 2, 3, 4, 5] * 5
n_ic = 500
lambda_ = 0.1
bandwidth = 1.5
delta = 0.08
n_observe = 6
h = 1.43
dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
            delta=delta, n_thread=15, N=10000, verbose=1)

1.43	372.96	3.71
CPU times: total: 15.6 ms
Wall time: 3min 48s


(372.9576, 3.7098814482708207)

In [123]:
%%time
size_list = [1, 2, 3]
for size_shift in size_list:
    dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
                delta=delta, n_shift=2, size_shift=size_shift, t_shift=30, n_thread=15, N=10000, verbose=1)

1.43	222.83	3.20
1.43	216.60	3.21
1.43	210.25	3.11
CPU times: total: 93.8 ms
Wall time: 9min 25s


#### Correlated data streams
##### $m=2$

In [34]:
%%time
distribution_type = [1] * 50
n_ic = 500
lambda_ = 0.1
bandwidth = 1.5
delta = 0.08
n_observe = 2
h = 1.76
dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
            delta=delta, n_thread=15, N=10000, verbose=1, data_ic_file=data_ic, bootstrap_flag=True)

1.76	364.54	3.52
CPU times: total: 31.2 ms
Wall time: 2min 5s


(364.5363, 3.515245722311742)

In [35]:
%%time
RL = np.zeros((3, 10000))
for i in range(3):
    RL[i] = dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
                             delta=delta, n_thread=15, N=10000, verbose=1, data_ic_file=data_ic, bootstrap_flag=False, data_ol_file=data_ol[i],
                             debug=True)
RL -= 30
print(np.mean(RL, axis=1))
print(np.std(RL, axis=1))

[195.8442 196.9223 194.4754]
[195.8442 196.9223 194.4754]
[193.44924897 197.72694015 195.02681814]
CPU times: total: 12.1 s
Wall time: 3min 31s


##### $m=4$

In [53]:
%%time
distribution_type = [1] * 50
n_ic = 500
lambda_ = 0.1
bandwidth = 1.5
delta = 0.08
n_observe = 4
h = 3.05
dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
            delta=delta, n_thread=15, N=5000, verbose=1, data_ic_file=data_ic, bootstrap_flag=True)

3.05	380.51	5.27
CPU times: total: 0 ns
Wall time: 1min


(380.5136, 5.271999617128969)

In [59]:
%%time
distribution_type = [1] * 50
n_ic = 500
lambda_ = 0.1
bandwidth = 1.5
delta = 0.08
n_observe = 4
h = 2.45
RL = np.zeros((3, 10000))
for i in range(3):
    RL[i] = dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
                        delta=delta, n_thread=15, N=10000, verbose=1, data_ic_file=data_ic, bootstrap_flag=False, data_ol_file=data_ol[i],
                        debug=True)
RL -= 30
print(np.mean(RL, axis=1))
print(np.std(RL, axis=1))

[131.988  131.7054 128.805 ]
[145.8077661  149.65816453 147.46112835]
CPU times: total: 13.6 s
Wall time: 2min 30s


##### $m=6$

In [62]:
%%time
distribution_type = [1] * 50
n_ic = 500
lambda_ = 0.1
bandwidth = 1.5
delta = 0.08
n_observe = 6
h = 3.5
dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
            delta=delta, n_thread=15, N=1000, verbose=1, data_ic_file=data_ic, bootstrap_flag=True)

3.50	191.33	5.75
CPU times: total: 0 ns
Wall time: 7.62 s


(191.326, 5.7451828277261985)

In [63]:
%%time
distribution_type = [1] * 50
n_ic = 500
lambda_ = 0.1
bandwidth = 1.5
delta = 0.08
n_observe = 6
h = 3.5
RL = np.zeros((3, 10000))
for i in range(3):
    RL[i] = dm.arl_SRAS(n_observe=n_observe, distribution_type=distribution_type, n_ic=n_ic, lambda_=lambda_, h=h, bandwidth=bandwidth,
                        delta=delta, n_thread=15, N=10000, verbose=1, data_ic_file=data_ic, bootstrap_flag=False, data_ol_file=data_ol[i],
                        debug=True)
RL -= 30
print(np.mean(RL, axis=1))
print(np.std(RL, axis=1))

[199.4558 193.3853 191.5529]
[213.15641216 214.53315745 215.82517787]
CPU times: total: 15.8 s
Wall time: 3min 48s
